version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login-password | docker login --username AWS --password-stdin 671891526111.dkr.ecr.us-east-1.amazonaws.com)
      - REPOSITORY_URI=public.ecr.aws/g9d5g9g8/docker
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - echo "Image pushed: $REPOSITORY_URI:$IMAGE_TAG"
artifacts:
  files:
    - imagedefinitions.json
